# access_key_id: $AWS_ACCESS_KEY
# secret_access_key: u3RFUOTPEowkOMcl6FhU+tBzKiPho+XZ1bDucZ0D
sudo: required
services:
  - docker

before_install:
  - docker build -t tim1016/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true tim1016/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-east-2-206906725218"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
